version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8  # Updated to CircleCI's modern Python image
    steps:
      - checkout  # Checkout your code from the repository

      - setup_remote_docker:
          version: 24.0  # Latest stable Docker version
          docker_layer_caching: true  # Optional: enables layer caching

      - run:
          name: Build Docker Image
          command: |
            docker build -t my-playwright-app .

      - run:
          name: Run Playwright Tests
          command: |
            docker run --rm -v $PWD/playwright-report:/repo/playwright-report my-playwright-app

      - store_artifacts:
          path: playwright-report  # Path to the Playwright report directory
          destination: playwright-report  # Directory in CircleCI where artifacts will be stored

      - store_test_results:
          path: playwright-report  # Path to the test results JSON file or directory

workflows:
  test:
    jobs:
      - build